# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'FLEXI Documentation'
copyright = '2026, Institute for Aerodynamics and Gas Dynamics (University of Stuttgart)'
author = 'Institute for Aerodynamics and Gas Dynamics (University of Stuttgart)'
release = '25.10'

# The language for content autogenerated by Sphinx
language = 'en'

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'friendly'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
#    'sphinx.ext.autosectionlabel',   # suppress warnings about duplicate labels due to duplicate section titles
#    'sphinxcontrib.spelling',        # run spell-checking by specifying '-b spelling' as builder (see buildHTL.sh)
    'sphinxcontrib.bibtex',
    'sphinx_rtd_theme',
    'sphinx_rtd_size',
    #'myst_parser',                   # reads only md-files -> comment out since already loaded by myst_nb, otherwise error "Config value 'myst_commonmark_only' already present"
    'myst_nb',                        # enable Jupyter Notebook support for .ipynb files (reads both md- and ipynb-files) -> comment out to not read ipynb-files when compiling PDF/HTML, comment in for HTML build e.g. to parse code-cell directives
    'sphinx.ext.mathjax'              # enhanced math rendering support for LaTeX expressions
]

# Set width
sphinx_rtd_size_width='98%'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    '_build', 'Thumbs.db', '.DS_Store',
    '**/.jupyter_cache/**',          # Exclude Jupyter execution cache files
    '**/jupyter_execute/**',         # Exclude Jupyter execution output directories
    '.ipynb_checkpoints'             # Exclude Jupyter notebook checkpoint files
]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

html_theme_options = {
    # Toc options
    'collapse_navigation': False,
    'navigation_depth': 4,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# For scaling, simply comment in the following line and html_css_files = [ ..
# and adjust the file _static/custom.css to your liking
html_static_path = ['_static']

# HTML option added in Sphinx 1.8.0b1 (released Sep 2018)
html_css_files = [
    'custom.css',
]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = 'https://numericsresearchgroup.org/images/icons/flexi.svg'
html_logo = './figures/flexi_logo_shade.webp'
# html_logo = 'https://numericsresearchgroup.org/images/icons/flexi.png'

# Also add custom css to the LaTeX output
def setup (app):
    app.add_css_file('custom.css')


# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
    'figure_align': 'htbp',
}

# latex config
master_doc = 'index'
root_doc   = 'index'              # modern replacement for deprecated master_doc

# replace strings to obtain correct line breaks
latex_documents = [
    (master_doc, 'foo.tex', project,
     author.replace(', ', '\\and ').replace(' and ', '\\and and '),
     'manual'),
]

# -- Bibliography ------------------------------------------------------------
bibtex_bibfiles = ['references.bib']

# -- Section labelling -------------------------------------------------------
# Make sure the target is unique
autosectionlabel_prefix_document = True

# -- Table and Figure labelling ----------------------------------------------
# Activate using: {numref}`tab:some-name` -> Table 1
numfig = True

# -- MyST-Parser Syntax Extensions -------------------------------------------
# https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#math-shortcuts
#
#   "dollarmath" for parsing of dollar $ and $$ encapsulated math.
#   "amsmath" for direct parsing of amsmath LaTeX environments.
#
myst_enable_extensions = [
    "amsmath",
    "dollarmath",
    "colon_fence",                   # Enable ::: fence syntax for directives, e.g. for admonitions
    "deflist",                       # Enable definition list syntax
    "tasklist",                      # Enable task list (checkbox) syntax
    "linkify"                        # Automatically convert URLs to links (pip install linkify-it-py)
]

suppress_warnings = ["myst.header"]

# -- Jupyter Notebook Execution Settings ------------------------------------
# Configure how Jupyter notebooks are executed during documentation build
nb_execution_mode = "off"          # do not build when compiling PDF/HTML - alternative: "cache" for caching execution results to speed up subsequent builds
nb_execution_timeout = 180         # Maximum execution time per cell (3 minutes)
